import React from 'react'
import Faq from './Faq';

const Privacy = () => {
  return (
    <div className="p-11">
      <h1 className="text-[#021caf] font-bold text-2xl pb-5">Privacy Policy</h1>
      <div className="">
        <h2 className="text-[24px] text-[#021caf] font-bold pt-1 pb-3">
          The Red Pen’s Privacy Policy For End-User
        </h2>
        <p className="text-[#404040] text-[20px] pb-4">
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and the European Union’s Regulation (EU) 2016/679
          (the General Data Protection Regulation) (hereinafter referred to as
          ‘GDPR’), as applicable. This electronic record is generated by a
          computer system and does not require any physical or digital
          signatures. Bay Education Partners LLP, a limited liability
          partnership firm, duly formed and incorporated under the provisions of
          the Limited Liability Partnership Act, 2008 allotted LLP
          Identification Number AAC0788, having its registered office at The
          Imperial, B. B. Nakashe Marg, Tardeo, Mumbai 400034 and operating
          under its trade name ‘The Red Pen’, (hereinafter referred to as ‘TRP’)
          is the owner of the website with domain name https://theredpen.in/
          (hereinafter referred to as the ‘Website’).
        </p>
        <p className="text-[#404040] text-[20px] pb-4">
          TRP is concerned about the privacy of the Users (defined hereinafter)
          who access the Website and provide, share, transfer or otherwise
          transmit data on the Website. This Privacy Policy is for the purpose
          of acquainting the Users with the manner in which TRP collects,
          processes, uses, shares, discloses and protects the User’s information
          collected through the Website; acquainting the Users of their rights
          and acquiring User’s consent to process the User’s Personally
          Identifiable Information.
        </p>
        <p className="text-[#404040] text-[20px] pb-4">
          Please read the following terms of TRP’s Privacy Policy:
        </p>
      </div>
      <Faq />
      {/* email section */}
      <div className="mt-4 flex flex-col xl:flex-row lg:flex-row md:flex-col sm:flex-col ">
        <div className='pb-5'>
          <p className="text-[#021caf] border-4 border-l-red-700 border-[#ffffff]  pl-2">
            Email Us
          </p>
          <p className="text-[#021caf] font-bold pl-3">
            inquiries@theredpen.in
          </p>
        </div>
        <div className='xl:ml-3'>
          <p className="text-[#021caf] border-4 border-l-red-700 border-[#ffffff] pl-2">
            Call Us
          </p>
          <p className="text-[#021caf] font-bold pl-3">91 98204 91179</p>
        </div>
        <div className='xl:ml-3'>
          <p className="text-[#021caf] border-4 border-l-red-700 border-[#ffffff] pl-2">
            Meet Us
          </p>
          <p className="text-[#021caf] font-bold pl-3">
            PRASAD CHAMBERS #411, TATA ROAD, NO-2, OPERA HOUSE, MUMBAI – 400004.
          </p>
        </div>
      </div>
    </div>
  );
}

export default Privacy
